x-kos-sdk-path: &kos_sdk_path /opt/KasperskyOS-Community-Edition-1.2.0.89

services:
  controlsys:
    build:
      context: ..
      dockerfile: docker/kos/Dockerfile
    working_dir: /workspace
    entrypoint: ["/usr/local/bin/run_env.sh"]
    command: ["/usr/local/bin/kos-run.sh", "run"]
    volumes:
      - ..:/workspace
      - type: bind
        source: *kos_sdk_path
        target: *kos_sdk_path
        read_only: true
    environment:
      KOS_PROJECT_ROOT: /workspace
      KOS_SDK_PREFIX: *kos_sdk_path
      CONTROL_SYS_QEMU_HOSTFWD: ",hostfwd=tcp::28081-:8081,hostfwd=tcp::28082-:8082"
    stdin_open: true
    tty: true
    ports:
      - "28081:28081"
      - "28082:28082"

  input:
    build:
      context: ..
      dockerfile: docker/modules/Dockerfile
    environment:
      MODULE_NAME: input
      TARGET_HOST: controlsys
      TARGET_PORT: "28082"
      HEARTBEAT_INTERVAL: "5"
    depends_on:
      - controlsys
    stdin_open: true
    tty: true

  card_reader:
    build:
      context: ..
      dockerfile: docker/modules/Dockerfile
    environment:
      MODULE_NAME: card-reader
      TARGET_HOST: controlsys
      TARGET_PORT: "28081"
      HEARTBEAT_INTERVAL: "5"
    depends_on:
      - controlsys
    stdin_open: true
    tty: true

  printer:
    build:
      context: ..
      dockerfile: docker/modules/Dockerfile
    environment:
      MODULE_NAME: printer
      TARGET_PORT: "0"
    depends_on:
      - controlsys

  netgw:
    build:
      context: ..
      dockerfile: docker/modules/Dockerfile
    environment:
      MODULE_NAME: netgw
      TARGET_HOST: controlsys
      TARGET_PORT: "9090"
      HEARTBEAT_INTERVAL: "6"
    depends_on:
      - controlsys

  bank:
    build:
      context: ..
      dockerfile: docker/modules/Dockerfile
    environment:
      MODULE_NAME: bank
      MODULE_MODE: server
      LISTEN_PORT: "10090"
    ports:
      - "10090:10090"
